spring.application.name=kosmo163_boot

server.port=80

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

#------ DB 연결정보

# DB 서버의 IP 정보 / port 정보
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe

# id 정보 (띄어쓰기 금지> 띄어쓰기도 하나의 글자로 인식)
spring.datasource.hikari.username=cns

# pw 정보
spring.datasource.hikari.password=cns

# 사용 DB - JDBC 정보
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver

# ----- mybatis 설정 정보
mybatis.mapper-locations=classpath:database/mappers/*Mappers.xml

mybatis.configuration.map-underscore-to-camel-case=true